[v1.x] Save/Load Gluon Blocks & HybridBlocks
apache/incubator-mxnet pull request #19565
Opened 2020-11-19 08:02 UTC by samskalicky

## Description ##
v1.x branch version of PoC for saving & loading Gluon Blocks & HybridBlocks from #19535

2020-11-21 01:50 UTC, samskalicky commented on python/mxnet/symbol/symbol.py
> +    - `/path-to/my-local-symbol`
should revert this so its indented again

2020-11-21 01:51 UTC, samskalicky commented on python/mxnet/contrib/quantization.py
> +        return Symbol.load(symbol_file_path)
this change isnt needed, should revert all changes in this file

2020-12-10 22:42 UTC, leezu approved these changes

2020-12-12 02:05 UTC, samskalicky commented on python/mxnet/contrib/quantization.py
> +        return Symbol.load(symbol_file_path)
done

2020-12-12 02:05 UTC, samskalicky commented on python/mxnet/symbol/symbol.py
> +    - `/path-to/my-local-symbol`
done

2020-12-14 19:08 UTC, leezu requested changes
Must not change `load_json` -> `fromjson` in the 1.x branch due to API compatibility

2020-12-14 22:14 UTC, samskalicky commented
> Must not change `load_json` -> `fromjson` in the 1.x branch due to API compatibility

backed out the change

2020-12-14 22:55 UTC, leezu approved these changes
Thanks @samskalicky

2020-12-15 18:12 UTC, merged