Fix DNNL requantize operator overflow error
apache/incubator-mxnet pull request #21079
Opened 2022-06-22 09:01 UTC by anko-intel

## Description ##
It fixes overflow issue which sometimes happenes giving negative scales.

## Checklist ##
### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

## Note ##
Simple way to reproduce the bug: 
MXNET_TEST_SEED=970044477 pytest tests/python/dnnl/subgraphs/test_fc_subgraph.py::test_add_quantized[ele_add-no_broadc-nore-full-none-int8]
but with modyfied shape to 
 ` data_shape = (4,6)`

2022-06-22 15:43 UTC, anko-intel commented
@mxnet-bot run ci [edge, website,windows-gpu]

2022-06-22 19:32 UTC, anko-intel commented
@mxnet-bot run ci [website]

2022-06-23 05:56 UTC, agrabows approved these changes

2022-06-23 09:56 UTC, bartekkuncer requested changes

2022-06-23 09:56 UTC, bartekkuncer commented on src/operator/quantization/dnnl/dnnl_requantize-inl.h
> +    // It doesn't use MaxAbs as it convert data to float which could cause overflow errors
```suggestion
    // MaxAbs is not used here as it converts data to float which could cause overflow errors.
```

2022-06-23 13:32 UTC, bartekkuncer approved these changes

2022-06-24 06:15 UTC, anko-intel commented
@mxnet-bot run ci [centos-gpu, unix-cpu, unix-gpu, windows-gpu]

2022-06-24 12:55 UTC, anko-intel commented
@mxnet-bot run ci [centos-gpu, unix-cpu, windows-gpu]

2022-06-24 19:28 UTC, anko-intel commented
@mxnet-bot run ci [centos-gpu]

2022-07-05 07:41 UTC, bgawrych approved these changes

2022-07-05 07:42 UTC, merged