Add support for bool data type for condition in where operator
apache/incubator-mxnet pull request #21103
Opened 2022-07-20 12:58 UTC by bgawrych

## Description ##
This change allows to utilize bool data type for condition tensor in oneDNN implementation of where operator

## Checklist ##
### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

2022-07-21 21:46 UTC, bartekkuncer requested changes

2022-07-21 21:46 UTC, bartekkuncer commented on src/operator/nn/dnnl/dnnl_where.cc
> +           SupportDNNL<DNNLTypeMode::NoInt32, DNNLTensorsDtypes::AllSame>({inputs[1], inputs[2]});
```suggestion
    return SupportDNNLShape<1, 12>(inputs[0].shape()) &&
           SupportDNNL<DNNLTypeMode::NoInt32, DNNLTensorsDtypes::AllSame>({inputs[1], inputs[2]});
```
If you insist on keeping the variable please make it const.

2022-07-21 21:46 UTC, bartekkuncer commented on src/operator/nn/dnnl/dnnl_where.cc
> + * \return deducted broadcasted shape basing on first_shape and second_shape
```suggestion
 * \return deducted broadcasted shape based on first_shape and second_shape
```

2022-08-01 06:02 UTC, bgawrych commented
@mxnet-bot run ci [centos-cpu, unix-cpu, unix-gpu]

2022-08-02 11:14 UTC, bartekkuncer commented on src/operator/nn/dnnl/dnnl_where.cc
> +    // to allow using bool datatype for 'condition' tensor - data will be treated as uint8
data type or datatype?

2022-08-09 07:48 UTC, bgawrych commented
@mxnet-bot run ci [centos-gpu]

2022-08-11 13:53 UTC, bartekkuncer approved these changes

2022-08-12 07:25 UTC, merged